import React from 'react';

export const glossaryTranslations: Record<string, Record<string, { definition: string; details: string }>> = {
    en: {
        "RAG (Retrieval-Augmented Generation)": {
            definition: "AI technique that optimizes Large Language Model (LLM) responses by retrieving information from a secure external database before generating the answer.",
            details: "RAG anchors the model's response in actual company facts (like manuals, ERP, and CRM), reducing the probability of hallucinations (factual errors) to practically zero."
        },
        "MCP (Model Context Protocol)": {
            definition: "Open protocol developed by Anthropic that establishes a universal and secure standard for connecting Artificial Intelligence models to data sources and software tools.",
            details: "Acts as a 'USB' standard for AIs, allowing a single MCP server to provide context and tools to different AI clients without the need for bespoke proprietary integrations for each LLM."
        },
        "LLM (Large Language Model)": {
            definition: "Deep learning Artificial Intelligence models trained on vast textual datasets to understand, generate, translate, and reason in natural language.",
            details: "Prominent examples include ChatGPT (OpenAI), Claude (Anthropic), Gemini (Google), and Llama (Meta), serving as the core cognitive processing tools in modern systems."
        },
        "Vector Database (Banco de Dados Vetorial)": {
            definition: "Database designed to store and search embeddings (mathematical vectors representing the semantic meaning of content).",
            details: "Tools like Pinecone, Qdrant, and pgvector allow semantic searches to be performed in milliseconds, finding document snippets conceptually similar to the user's question."
        },
        "Embedding (Vetorização)": {
            definition: "The process of converting text, images, or audio into sequences of numbers (vectors) that capture the conceptual meaning and context of the information.",
            details: "Thanks to embeddings, a search for 'development pricing' can return an article about 'software costs', as the algorithm understands the semantic equivalence."
        },
        "Prompt Injection (Injeção de Prompt)": {
            definition: "A security vulnerability where a malicious user manipulates AI inputs to make it ignore its original guidelines and expose secrets or execute forbidden actions.",
            details: "Shielding systems against Prompt Injection involves creating intermediary validation architectures and sanitizing all input strings before processing by the LLM."
        },
        "DOM Bloating (Inchaço do DOM)": {
            definition: "An excess of nested and unnecessary elements in the HTML tree of a web page, usually generated by visual builders or pre-made templates.",
            details: "Increases browser processing time and delays loading, harming Core Web Vitals scores (such as LCP) and Google Lighthouse ratings."
        },
        "Headless Commerce (Comércio Desacoplado)": {
            definition: "An e-commerce architecture where the front presentation layer (Frontend) is completely separated from the backend e-commerce logic (Backend).",
            details: "Communication occurs via fast APIs. Allows creating ultra-fast custom interfaces in Next.js while robust tools like VTEX or Shopify manage the shopping cart."
        },
        "Core Web Vitals": {
            definition: "A set of web performance metrics established by Google that assess the actual user experience in terms of loading speed, interactivity, and visual stability.",
            details: "Composed mainly of LCP (loading), INP (click interactivity), and CLS (visual stability). It is a direct SEO ranking factor."
        },
        "LCP (Largest Contentful Paint)": {
            definition: "Core Web Vitals metric that measures the time required to render the largest visual element (usually a hero image or title block) on the user's screen.",
            details: "To ensure a good experience and SEO score, LCP must happen in less than 2.5 seconds. At GHWD, we optimize code to achieve LCP under 1.0 second."
        },
        "INP (Interaction to Next Paint)": {
            definition: "Metric that evaluates the interactivity latency of a web page, measuring the time elapsed from the user's click to the subsequent visual update on the screen.",
            details: "Replaced the old FID in 2024. A good INP value is below 200 milliseconds. It is crucial for interactive systems like dashboards and e-commerces."
        },
        "CLS (Cumulative Layout Shift)": {
            definition: "Core Web Vitals metric that measures the visual instability of a page, observing if textual elements or buttons change places unexpectedly during loading.",
            details: "Unstable layouts cause accidental clicks and frustration. A good CLS index should be less than 0.1 and is avoided by reserving fixed sizes for media and fonts."
        },
        "SSG (Static Site Generation)": {
            definition: "Process of compiling web pages into pure static HTML files during build time, before the user accesses them.",
            details: "Eliminates the need for real-time database queries, allowing pages to be served via CDN Edge in milliseconds with unmatched performance."
        },
        "SSR (Server-Side Rendering)": {
            definition: "Rendering strategy where the Next.js server generates the dynamic HTML of a page on-demand for each user request.",
            details: "Useful for personalized pages, containing dynamic account or cart data, which still require SEO indexing on the first load."
        },
        "API (Application Programming Interface)": {
            definition: "Set of rules and specifications that allows different software applications to communicate and exchange data with each other.",
            details: "At GHWD, we create secure REST and GraphQL APIs to integrate legacy ERPs, commercial CRMs, and databases into Next.js interfaces and AI pipelines."
        },
        "Webhook": {
            definition: "An HTTP communication pattern that sends real-time data from one system to another immediately after a specific event occurs.",
            details: "Example: When an invoice is paid, the gateway sends a Webhook containing payment data to notify GHWD's automation to release the product automatically."
        },
        "n8n": {
            definition: "A powerful fair-code workflow automation tool focused on API integration and complex data flows.",
            details: "Can be hosted on the company's own infrastructure (on-premise), ensuring data security and eliminating variable costs based on volume of executions."
        },
        "Schema.org": {
            definition: "A collaborative, structured vocabulary of semantic tags and markups that developers add to HTML to help search engines understand the meaning of data.",
            details: "Essential for SEO and GEO, as they allow search engines like Google and ChatGPT to extract prices, dates, FAQs, and authors in a 100% structured format."
        },
        "Token": {
            definition: "The basic unit of text that an Artificial Intelligence model processes. It can be a word, part of a word, or special character.",
            details: "AI models charge per thousand tokens consumed. Optimizing prompts and RAG contexts aims to reduce token waste and lower the monthly bill."
        },
        "Serverless (Sem Servidor)": {
            definition: "Cloud execution model where the provider automatically manages the allocation of physical servers to run small code functions on-demand.",
            details: "Eliminates idle server costs and ensures unlimited scalability. If the site has zero visits, the cost is zero; if it has millions, it scales without crashing."
        }
    },
    es: {
        "RAG (Retrieval-Augmented Generation)": {
            definition: "Técnica de IA que optimiza las respuestas de Modelos de Lenguaje (LLMs) al recuperar información de una base de datos externa segura antes de generar la respuesta.",
            details: "RAG ancla la respuesta del modelo en datos reales de su empresa (como manuales, ERP y CRM), reduciendo la probabilidad de alucinaciones (errores fácticos) a prácticamente cero."
        },
        "MCP (Model Context Protocol)": {
            definition: "Protocolo abierto desarrollado por Anthropic que establece un estándar universal y seguro para conectar modelos de Inteligencia Artificial a fuentes de datos y herramientas de software.",
            details: "Actúa como un estándar 'USB' para las IA, permitiendo que un único servidor MCP proporcione contexto y herramientas a diferentes clientes de IA sin necesidad de integraciones propietarias a medida."
        },
        "LLM (Large Language Model)": {
            definition: "Modelos de Inteligencia Artificial de aprendizaje profundo entrenados en vastos conjuntos de datos textuales para comprender, generar, traducir y razonar en lenguaje natural.",
            details: "Ejemplos destacados incluyen ChatGPT (OpenAI), Claude (Anthropic), Gemini (Google) y Llama (Meta), siendo las herramientas básicas de procesamiento cognitivo en sistemas modernos."
        },
        "Vector Database (Banco de Dados Vetorial)": {
            definition: "Base de datos diseñada para almacenar y buscar embeddings (vectores matemáticos que representan el significado semántico del contenido).",
            details: "Herramientas como Pinecone, Qdrant y pgvector permiten realizar búsquedas semánticas en milisegundos, encontrando fragmentos de documentos conceptualmente similares a la pregunta del usuario."
        },
        "Embedding (Vetorização)": {
            definition: "El proceso de convertir textos, imágenes o audios en secuencias de números (vectores) que capturan el significado conceptual y el contexto de la información.",
            details: "Gracias a los embeddings, una búsqueda de 'costos de desarrollo' puede devolver un artículo sobre 'precios de software', ya que el algoritmo comprende la equivalencia de sentido."
        },
        "Prompt Injection (Injeção de Prompt)": {
            definition: "Una vulnerabilidad de seguridad donde un usuario malintencionado manipula las entradas de una IA para hacerla ignorar sus directrices originales y exponer secretos o ejecutar acciones prohibidas.",
            details: "Proteger sistemas contra el Prompt Injection implica crear arquitecturas de validación intermedias y sanitizar todas las cadenas de entrada antes de ser procesadas por el LLM."
        },
        "DOM Bloating (Inchaço do DOM)": {
            definition: "El exceso de elementos anidados e innecesarios en el árbol HTML de una página web, generalmente generado por constructores visuales o plantillas prefabricadas.",
            details: "Aumenta el tiempo de procesamiento de los navegadores y retrasa la carga, afectando los índices de Core Web Vitals (como LCP) y la puntuación de Google Lighthouse."
        },
        "Headless Commerce (Comércio Desacoplado)": {
            definition: "Una arquitectura de comercio electrónico donde la capa visual de presentación (Frontend) se separa completamente de la lógica de comercio electrónico (Backend).",
            details: "La comunicación ocurre a través de API rápidas. Permite crear interfaces personalizadas ultrarrápidas en Next.js mientras herramientas robustas como VTEX o Shopify gestionan el carrito de compras."
        },
        "Core Web Vitals": {
            definition: "Conjunto de métricas de rendimiento web establecidas por Google que evalúan la experiencia real del usuario en términos de velocidad de carga, interactividad y estabilidad visual.",
            details: "Compuesto principalmente por LCP (carga), INP (interactividad al hacer clic) y CLS (estabilidad visual). Es un factor directo de posicionamiento SEO."
        },
        "LCP (Largest Contentful Paint)": {
            definition: "Métrica de Core Web Vitals que mide el tiempo necesario para renderizar el elemento visual más grande (generalmente una imagen de cabecera o bloque de título) en la pantalla del usuario.",
            details: "Para garantizar una buena experiencia y puntuación SEO, el LCP debe ocurrir en menos de 2,5 segundos. En GHWD, optimizamos el código para lograr un LCP menor a 1,0 segundo."
        },
        "INP (Interaction to Next Paint)": {
            definition: "Métrica que evalúa la latencia de interactividad de una página web, midiendo el tiempo transcurrido desde el clic del usuario hasta la subsiguiente actualización visual en pantalla.",
            details: "Reemplazó al antiguo FID en 2024. Un buen valor de INP está por debajo de los 200 milisegundos. Es crucial para sistemas interactivos como dashboards y e-commerces."
        },
        "CLS (Cumulative Layout Shift)": {
            definition: "Métrica de Core Web Vitals que mide la inestabilidad visual de una página, observando si elementos de texto o botones cambian de lugar inesperadamente durante la carga.",
            details: "Los diseños inestables causan clics accidentales y frustración. El índice CLS debe ser inferior a 0.1 y se evita reservando tamaños fijos para medios y fuentes."
        },
        "SSG (Static Site Generation)": {
            definition: "Proceso de compilar páginas web en archivos HTML estáticos puros durante el tiempo de compilación (build), antes de que el usuario acceda a ellos.",
            details: "Elimina la necesidad de consultas a bases de datos en tiempo real, lo que permite servir páginas a través de CDN Edge en milisegundos con un rendimiento insuperable."
        },
        "SSR (Server-Side Rendering)": {
            definition: "Estrategia de renderización donde el servidor Next.js genera el HTML dinámico de una página bajo demanda para cada solicitud del usuario.",
            details: "Útil para páginas personalizadas, que contienen datos dinámicos de cuentas o carritos, que aún así requieren indexación SEO en la primera carga."
        },
        "API (Application Programming Interface)": {
            definition: "Conjunto de reglas y especificaciones que permite que diferentes aplicaciones de software se comuniquen y compartan datos entre sí.",
            details: "En GHWD, creamos API REST y GraphQL seguras para integrar ERP heredados, CRM comerciales y bases de datos con interfaces Next.js y flujos de IA."
        },
        "Webhook": {
            definition: "Un patrón de comunicación HTTP que envía datos en tiempo real de un sistema a otro inmediatamente após la ocurrencia de un evento específico.",
            details: "Ejemplo: Cuando se paga una factura, la pasarela envía un Webhook con los datos del pago para notificar a la automatización de GHWD que libere el producto automáticamente."
        },
        "n8n": {
            definition: "Una potente herramienta de automatización de flujos de trabajo fair-code enfocada en la integración de API y flujos de datos complejos.",
            details: "Puede alojarse en la propia infraestructura de la empresa (on-premise), lo que garantiza la seguridad de los datos y elimina costos variables basados en el volumen de ejecuciones."
        },
        "Schema.org": {
            definition: "Un vocabulario colaborativo y estructurado de etiquetas y marcado semántico que los desarrolladores agregan al HTML para ayudar a los motores de búsqueda a comprender el significado de los datos.",
            details: "Esencial para SEO y GEO, ya que permite que motores como Google y ChatGPT extraigan precios, fechas, preguntas frecuentes y autores de forma estructurada."
        },
        "Token": {
            definition: "La unidad básica de texto que procesa un modelo de Inteligencia Artificial. Puede ser una palabra, parte de una palabra o un carácter especial.",
            details: "Los modelos de IA cobran por cada mil tokens consumidos. La optimización de prompts y contextos RAG busca reducir el desperdicio de tokens para disminuir la factura mensual."
        },
        "Serverless (Sem Servidor)": {
            definition: "Modelo de ejecución en la nube donde el proveedor gestiona automáticamente la asignación de servidores físicos para ejecutar pequeñas funciones de código bajo demanda.",
            details: "Elimina los costos de servidores inactivos y garantiza una escalabilidad ilimitada. Si el sitio tiene cero visitas, el costo es cero; si tiene millones, escala sin caerse."
        }
    }
};

export const kbArticlesTranslations: Record<string, Record<string, any>> = {
    "o-que-e-um-agente-de-ia-e-como-ele-difere-de-um-chatbot": {
        en: {
            title: "What is an AI Agent and how does it differ from a traditional Chatbot?",
            description: "Understand the autonomous AI revolution and how Artificial Intelligence agents overcome the limitations of rigid and static chatbots in B2B process automation.",
            category: "Artificial Intelligence",
            date: "June 26, 2026",
            tldr: "Traditional chatbots only respond to messages based on rigid rules. AI agents possess autonomy: they reason in a loop, create their own action plans, use external APIs (tools), and maintain memory to execute tasks from start to finish.",
            sections: [
                {
                    title: "1. The End of the Rigid Chatbot Era",
                    content: (
                        <div className="space-y-4">
                            <p className="text-zinc-300 leading-relaxed">
                                For years, companies used chatbots based on static flowcharts. If you've ever clicked 'Option 1' or 'Option 2' only to fall into an infinite loop with no useful answer, you know the limits of this model. These systems are reactive, don't understand context, and break at the slightest script deviation.
                            </p>
                            <p className="text-zinc-300 leading-relaxed">
                                The rise of Large Language Models (LLMs) gave birth to a new software category: **Autonomous AI Agents**. Instead of following pre-programmed decision trees, these systems use deep neural networks to reason, plan, and execute complex actions in the real world.
                            </p>
                        </div>
                    )
                },
                {
                    title: "2. Comparative Table: Chatbot vs. AI Agent",
                    content: (
                        <div className="space-y-6">
                            <p className="text-zinc-300 leading-relaxed">
                                To understand the shift, observe how the two technologies behave when facing real business requests:
                            </p>
                            <div className="overflow-x-auto border border-white/10 rounded-xl">
                                <table className="w-full min-w-[550px] text-left text-sm border-collapse">
                                    <thead>
                                        <tr className="bg-zinc-900 border-b border-white/10">
                                            <th className="p-4 font-bold text-white">Feature</th>
                                            <th className="p-4 font-bold text-zinc-400">Traditional Chatbot</th>
                                            <th className="p-4 font-bold text-emerald-400">AI Agent (Modern)</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr className="border-b border-white/5">
                                            <td className="p-4 font-semibold text-white">Comprehension</td>
                                            <td className="p-4 text-zinc-400">Exact keywords and rigid rules</td>
                                            <td className="p-4 text-zinc-300">Semantic context and fluid natural language</td>
                                        </tr>
                                        <tr className="border-b border-white/5">
                                            <td className="p-4 font-semibold text-white">Decision Making</td>
                                            <td className="p-4 text-zinc-400">Pre-defined flowchart by developer</td>
                                            <td className="p-4 text-zinc-300">Autonomous, goal-driven, and logical reasoning</td>
                                        </tr>
                                        <tr className="border-b border-white/5">
                                            <td className="p-4 font-semibold text-white">Tool Use</td>
                                            <td className="p-4 text-zinc-400">Limited to pre-programmed static integrations</td>
                                            <td className="p-4 text-zinc-300">Calls APIs, queries databases, and runs scripts dynamically</td>
                                        </tr>
                                        <tr>
                                            <td className="p-4 font-semibold text-white">Memory</td>
                                            <td className="p-4 text-zinc-400">Forgets data immediately after closing the chat</td>
                                            <td className="p-4 text-zinc-300">Long-term memory and history persistence</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    )
                },
                {
                    title: "3. An Agent's Operational Loop: ReAct Reasoning",
                    content: (
                        <div className="space-y-4">
                            <p className="text-zinc-300 leading-relaxed">
                                The secret behind an AI agent's autonomy is the framework known as **ReAct (Reason and Act)**. The agent works in a continuous loop composed of three main phases:
                            </p>
                            <ol className="list-decimal pl-6 space-y-3 text-zinc-300">
                                <li>**Perception (Thought):** The AI analyzes user input or system status and reasons about what needs to be done. It creates a mental plan: *'To answer this question about shipping, I first need to fetch the order status in the tracking API.'*</li>
                                <li>**Action (Tool Call):** The agent decides which external tool to use and executes the call. It converts its thought into a real API call to the shipping system.</li>
                                <li>**Observation (Reflection):** The AI receives the tool's response (e.g. *'Order delivered in New York on 06/25'*) and analyzes if the initial goal was met. If it needs more actions, it restarts the loop.</li>
                            </ol>
                        </div>
                    )
                },
                {
                    title: "4. Tools: Giving AI Hands and Eyes",
                    content: (
                        <div className="space-y-4">
                            <p className="text-zinc-300 leading-relaxed">
                                An isolated LLM is like a brilliant brain in a jar: it knows a lot but cannot interact with the world. Agents solve this by exposing **Tools**. These tools are structured code functions the agent can trigger whenever it deems necessary.
                            </p>
                            <div className="bg-zinc-900 border border-white/5 rounded-xl p-6 font-mono text-sm text-zinc-400 space-y-2">
                                <span className="text-emerald-400 block">// Example of a tool the agent can trigger</span>
                                <span>{"{"}</span>
                                <div className="pl-4">
                                    <span>"name": "check_inventory",</span><br />
                                    <span>"description": "Checks the real-time stock of an SKU in the ERP",</span><br />
                                    <span>"parameters": {"{ \"sku\": \"string\" }"}</span>
                                </div>
                                <span>{"}"}</span>
                            </div>
                            <p className="text-zinc-300 leading-relaxed">
                                If a customer asks if 'Obsidian Key v2' is available, the agent semantically identifies the intent, extracts the product name, maps it to the corresponding SKU, and runs the function <code className="text-emerald-400">check_inventory("OBS-KEY-V2")</code> invisibly to the final user.
                            </p>
                        </div>
                    )
                },
                {
                    title: "5. Practical Applications in the B2B Market",
                    content: (
                        <div className="space-y-4">
                            <p className="text-zinc-300 leading-relaxed">
                                At GHWD, we build agents integrated into our clients' systems to handle complex operational tasks:
                            </p>
                            <ul className="list-disc pl-6 space-y-3 text-zinc-300">
                                <li>**Level-2 Customer Support:** Agents that don't just answer questions, but cancel orders, issue duplicate invoices directly from the banking API, and reschedule deliveries by querying logistics databases.</li>
                                <li>**Lead Qualification and SDR:** WhatsApp inbound lead screening agents that talk to prospects, qualify intent based on internal criteria, and schedule meetings on the salesperson's calendar using Calendly.</li>
                                <li>**Autonomous Financial Analyst:** AI bots that monitor cash flow, identify payment delays, and compose personalized collection notices with exact invoice details.</li>
                            </ul>
                        </div>
                    )
                }
            ],
            faqItems: [
                {
                    q: "Can AI agents make decisions without human supervision?",
                    a: "Yes, they have the technical autonomy to make operational decisions based on the rules we calibrate in the system prompts. However, for high-risk processes (like financial transactions above certain values), we implement 'Human-in-the-loop' (HITL) mechanisms, where the AI does the processing but requires human approval to finalize."
                },
                {
                    q: "What is the cost difference between an AI agent and a human?",
                    a: "An agent's operational cost is measured by API token consumption (fractions of a cent per interaction) and fixed infrastructure. In scale, an AI agent can handle thousands of complex requests monthly for under $40 in cloud costs, working 24/7 without limitations."
                }
            ]
        },
        es: {
            title: "¿Qué es un Agente de IA y cómo se diferencia de un Chatbot tradicional?",
            description: "Entienda la revolución de la IA autónoma y cómo los agentes de Inteligencia Artificial superan las limitaciones de los chatbots rígidos y estáticos en la automatización de procesos B2B.",
            category: "Inteligencia Artificial",
            date: "26 de Junio de 2026",
            tldr: "Los chatbots tradicionales solo responden mensajes basados en reglas rígidas. Los agentes de IA poseen autonomía: razonan en bucle, crean sus propios planes de acción, utilizan API externas (herramientas) y mantienen memoria para ejecutar tareas de principio a fin.",
            sections: [
                {
                    title: "1. El Fin de la Era del Chatbot Rígido",
                    content: (
                        <div className="space-y-4">
                            <p className="text-zinc-300 leading-relaxed">
                                Durante años, las empresas utilizaron chatbots basados en diagramas de flujo estáticos. Si alguna vez ha hecho clic en 'Opción 1' u 'Opción 2' solo para caer en un bucle infinito sin respuesta útil, conoce las limitaciones de este modelo. Estos sistemas son reactivos, no entienden el contexto y se rompen ante la menor desviación.
                            </p>
                            <p className="text-zinc-300 leading-relaxed">
                                El auge de los Grandes Modelos de Lenguaje (LLM) dio origen a una nueva categoría de software: los **Agentes de IA Autónomos**. En lugar de seguir árboles de decisión preprogramados, estos sistemas utilizan redes neuronales profundas para razonar, planificar y ejecutar acciones complejas en el mundo real.
                            </p>
                        </div>
                    )
                },
                {
                    title: "2. Tabla Comparativa: Chatbot vs. Agente de IA",
                    content: (
                        <div className="space-y-6">
                            <p className="text-zinc-300 leading-relaxed">
                                Para comprender el cambio, observe cómo se comportan ambas tecnologías ante solicitudes de negocio reales:
                            </p>
                            <div className="overflow-x-auto border border-white/10 rounded-xl">
                                <table className="w-full min-w-[550px] text-left text-sm border-collapse">
                                    <thead>
                                        <tr className="bg-zinc-900 border-b border-white/10">
                                            <th className="p-4 font-bold text-white">Característica</th>
                                            <th className="p-4 font-bold text-zinc-400">Chatbot Tradicional</th>
                                            <th className="p-4 font-bold text-emerald-400">Agente de IA (Moderno)</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr className="border-b border-white/5">
                                            <td className="p-4 font-semibold text-white">Comprensión</td>
                                            <td className="p-4 text-zinc-400">Palabras clave exactas y reglas rígidas</td>
                                            <td className="p-4 text-zinc-300">Contexto semántico y lenguaje natural fluido</td>
                                        </tr>
                                        <tr className="border-b border-white/5">
                                            <td className="p-4 font-semibold text-white">Toma de Decisiones</td>
                                            <td className="p-4 text-zinc-400">Diagrama de flujo predefinido por el programador</td>
                                            <td className="p-4 text-zinc-300">Autónoma, orientada a objetivos y razonamiento lógico</td>
                                        </tr>
                                        <tr className="border-b border-white/5">
                                            <td className="p-4 font-semibold text-white">Uso de Herramientas</td>
                                            <td className="p-4 text-zinc-400">Limitado a integraciones estáticas preprogramadas</td>
                                            <td className="p-4 text-zinc-300">Llama API, consulta bases de datos y ejecuta scripts dinámicamente</td>
                                        </tr>
                                        <tr>
                                            <td className="p-4 font-semibold text-white">Memoria</td>
                                            <td className="p-4 text-zinc-400">Olvida los datos inmediatamente al cerrar el chat</td>
                                            <td className="p-4 text-zinc-300">Memoria a largo plazo y persistencia del historial</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    )
                },
                {
                    title: "3. El Bucle de un Agente: Razonamiento ReAct",
                    content: (
                        <div className="space-y-4">
                            <p className="text-zinc-300 leading-relaxed">
                                El secreto de la autonomía de un agente de IA es el framework conocido como **ReAct (Reason and Act)**. El agente funciona en un bucle continuo compuesto por tres fases:
                            </p>
                            <ol className="list-decimal pl-6 space-y-3 text-zinc-300">
                                <li>**Percepción (Pensamiento):** La IA analiza la entrada del usuario y razona sobre lo que debe hacerse. Crea un plan mental: *'Para responder a esta pregunta sobre el envío, primero debo buscar el estado en la API de seguimiento.'*</li>
                                <li>**Acción (Llamada a Herramienta):** El agente decide qué herramienta externa usar y ejecuta la llamada API real.</li>
                                <li>**Observación (Reflexión):** La IA recibe la respuesta (p. ej. *'Pedido entregado en Madrid el 25/06'*) y analiza si se cumplió el objetivo. Si necesita más acciones, reinicia el bucle.</li>
                            </ol>
                        </div>
                    )
                },
                {
                    title: "4. Herramientas: Dando Manos y Ojos a la IA",
                    content: (
                        <div className="space-y-4">
                            <p className="text-zinc-300 leading-relaxed">
                                Un LLM aislado es como un cerebro brillante en un frasco: sabe mucho pero no puede interactuar. Los agentes solucionan esto exponiendo **Herramientas (Tools)**, que son funciones de código estructuradas que el agente puede activar.
                            </p>
                            <div className="bg-zinc-900 border border-white/5 rounded-xl p-6 font-mono text-sm text-zinc-400 space-y-2">
                                <span className="text-emerald-400 block">// Ejemplo de herramienta que el agente puede activar</span>
                                <span>{"{"}</span>
                                <div className="pl-4">
                                    <span>"name": "consultar_inventario",</span><br />
                                    <span>"description": "Consulta el inventario en tiempo real en el ERP",</span><br />
                                    <span>"parameters": {"{ \"sku\": \"string\" }"}</span>
                                </div>
                                <span>{"}"}</span>
                            </div>
                            <p className="text-zinc-300 leading-relaxed">
                                Si un cliente pregunta por la disponibilidad del producto 'Obsidian Key v2', el agente identifica semánticamente la intención, extrae el SKU correspondiente y ejecuta la función <code className="text-emerald-400">consultar_inventario("OBS-KEY-V2")</code> de forma invisible.
                            </p>
                        </div>
                    )
                },
                {
                    title: "5. Aplicaciones Prácticas en el Mercado B2B",
                    content: (
                        <div className="space-y-4">
                            <p className="text-zinc-300 leading-relaxed">
                                En GHWD desarrollamos agentes integrados en los ecosistemas de nuestros clientes para automatizar tareas complejas:
                            </p>
                            <ul className="list-disc pl-6 space-y-3 text-zinc-300">
                                <li>**Atención al Cliente Nivel 2:** Agentes que no solo responden sino que cancelan pedidos, emiten duplicados de facturas directamente de la API bancaria y reprograman entregas.</li>
                                <li>**Calificación y SDR de Ventas:** Triaje de leads vía WhatsApp que conversan con el prospecto, lo cualifican y programan reuniones en la agenda usando Calendly.</li>
                                <li>**Analista Financiero Autónomo:** Bots de IA que monitorean flujos de caja, identifican retrasos de pagos sistemáticos y elaboran notificaciones de cobro personalizadas.</li>
                            </ul>
                        </div>
                    )
                }
            ],
            faqItems: [
                {
                    q: "¿Pueden los agentes de IA tomar decisiones sin supervisión humana?",
                    a: "Sí, poseen la autonomía técnica necesaria. Sin embargo, para procesos de alto riesgo (como transacciones financieras grandes), implementamos mecanismos 'Human-in-the-loop' (HITL), donde la IA hace el procesamiento pero requiere la aprobación de un analista humano."
                },
                {
                    q: "¿Cuál es la diferencia de costo operacional con un humano?",
                    a: "El costo de un agente se mide por consumo de tokens de API e infraestructura fija. A escala, un agente de IA puede procesar miles de casos por un costo en la nube inferior a $40 mensuales, sin límites de horarios."
                }
            ]
        }
    },
    "como-integrar-chatgpt-e-llms-a-sistemas-erp-crm-com-seguranca": {
        en: {
            title: "Practical Guide: How to Integrate ChatGPT and LLMs into ERP/CRM Systems Securely",
            description: "Understand the challenges of enterprise data security in AI integrations and how to design middleware that sanitizes PII and keeps databases protected.",
            category: "Integrations",
            date: "June 26, 2026",
            tldr: "Integrating LLMs with ERPs/CRMs requires a security-first approach. You should never connect a model directly to databases. Instead, build a sanitizing middleware that manages keys, strips PII, and runs validation layers.",
            sections: [
                {
                    title: "1. The Challenge of Enterprise Data Security in AI",
                    content: (
                        <div className="space-y-4">
                            <p className="text-zinc-300 leading-relaxed">
                                Connecting LLMs to systems containing ERP secrets (like orders, invoices, and accounting) or CRM records (PII) presents a massive security risk if not designed with strict access control. Traditional AI configurations send data straight to external providers, creating potential data leaks.
                            </p>
                        </div>
                    )
                }
            ],
            faqItems: []
        },
        es: {
            title: "Guía Práctica: Cómo Integrar ChatGPT y LLMs en Sistemas ERP/CRM de Forma Segura",
            description: "Comprenda los desafíos de la seguridad de datos corporativos en integraciones de IA y cómo diseñar middleware que elimine PII y mantenga protegidas las bases de datos.",
            category: "Integraciones",
            date: "26 de Junio de 2026",
            tldr: "Integrar LLMs con ERP/CRM requiere un enfoque de seguridad prioritario. Nunca debe conectar un modelo directamente a bases de datos. En su lugar, construya un middleware sanitizador que maneje claves y valide flujos.",
            sections: [
                {
                    title: "1. El Desafío de la Seguridad de Datos en IA Corporativa",
                    content: (
                        <div className="space-y-4">
                            <p className="text-zinc-300 leading-relaxed">
                                Conectar LLMs a sistemas que contienen secretos de ERP (como pedidos o facturación) o registros de CRM presenta un riesgo de seguridad masivo si no se diseña con un control de acceso estricto. Las configuraciones tradicionales de IA envían datos directamente a proveedores externos, creando posibles fugas.
                            </p>
                        </div>
                    )
                }
            ],
            faqItems: []
        }
    },
    "model-context-protocol-mcp-o-guia-definitivo-do-novo-padrao-de-integracao-de-ia": {
        en: {
            title: "Model Context Protocol (MCP): The Definitive Guide to the New AI Integration Standard",
            description: "Discover the open standard created by Anthropic that acts as a secure USB connection between AI models and local databases, files, and enterprise APIs.",
            category: "Artificial Intelligence",
            date: "June 26, 2026",
            tldr: "Model Context Protocol (MCP) is a universal standard that allows LLMs to query secure local data sources. Rather than writing unique integration code for every client, a single MCP server exposes resources, prompts, and tools in a standard JSON-RPC format.",
            sections: [
                {
                    title: "1. What is the Model Context Protocol (MCP)?",
                    content: (
                        <div className="space-y-4">
                            <p className="text-zinc-300 leading-relaxed">
                                MCP is an open standard that enables developers to build secure, two-way connections between AI models and data sources. Acting like a USB port for LLMs, it provides a unified protocol to fetch files, inspect databases, and call local shell commands securely.
                            </p>
                        </div>
                    )
                }
            ],
            faqItems: []
        },
        es: {
            title: "Model Context Protocol (MCP): La Guía Definitiva del Nuevo Estándar de Integración de IA",
            description: "Descubra el estándar abierto creado por Anthropic que actúa como una conexión USB segura entre modelos de IA y bases de datos locales, archivos y API corporativas.",
            category: "Inteligencia Artificial",
            date: "26 de Junio de 2026",
            tldr: "Model Context Protocol (MCP) es un estándar universal que permite a los LLM consultar fuentes de datos locales seguras de forma estandarizada mediante formato JSON-RPC.",
            sections: [
                {
                    title: "1. ¿Qué es el Model Context Protocol (MCP)?",
                    content: (
                        <div className="space-y-4">
                            <p className="text-zinc-300 leading-relaxed">
                                MCP es un estándar abierto que permite a los desarrolladores crear conexiones seguras y bidireccionales entre modelos de IA y fuentes de datos, actuando como un puerto USB para los LLM.
                            </p>
                        </div>
                    )
                }
            ],
            faqItems: []
        }
    },
    "o-que-e-rag-retrieval-augmented-generation-e-por-que-sua-empresa-precisa-dele": {
        en: {
            title: "What is RAG (Retrieval-Augmented Generation) and why does your business need it?",
            description: "Learn how RAG optimizes LLM responses by fetching facts from secure local databases before answering, eliminating hallucinations and keeping data private.",
            category: "Artificial Intelligence",
            date: "June 26, 2026",
            tldr: "Retrieval-Augmented Generation (RAG) is a pipeline that retrieves documents matching a user's question, feeds them into the prompt context, and instructs the LLM to write a factual answer based solely on the documents.",
            sections: [
                {
                    title: "1. The Open-Book Exam Analogy",
                    content: (
                        <div className="space-y-4">
                            <p className="text-zinc-300 leading-relaxed">
                                Traditional LLMs answer questions from memory, which leads to hallucinations. RAG turns it into an open-book exam: when a user asks a question, the system searches the company's internal files, finds the relevant chapters, and hands them to the AI to write a factual answer.
                            </p>
                        </div>
                    )
                }
            ],
            faqItems: []
        },
        es: {
            title: "¿Qué es RAG (Retrieval-Augmented Generation) y por qué su empresa lo necesita?",
            description: "Aprenda cómo RAG optimiza las respuestas de LLM al buscar datos reales en bases de datos locales antes de responder, eliminando alucinaciones.",
            category: "Inteligencia Artificial",
            date: "26 de Junio de 2026",
            tldr: "RAG es una arquitectura que recupera documentos relevantes, los inyecta en el prompt y obliga a la IA a responder basándose únicamente en esa información confiable.",
            sections: [
                {
                    title: "1. La Analogía del Examen con Consulta",
                    content: (
                        <div className="space-y-4">
                            <p className="text-zinc-300 leading-relaxed">
                                Los LLM tradicionales responden de memoria, lo que genera alucinaciones. RAG convierte el proceso en un examen con libro abierto, buscando en los archivos de la empresa antes de responder.
                            </p>
                        </div>
                    )
                }
            ],
            faqItems: []
        }
    },
    "como-automatizar-processos-corporativos-com-ia-e-plataformas-low-code-n8n-make": {
        en: {
            title: "How to Automate Corporate Processes with AI and Low-Code Platforms (n8n & Make)",
            description: "Explore the shift from traditional automation to cognitive workflows using self-hosted platforms like n8n combined with LLM processing.",
            category: "Business Automation",
            date: "June 26, 2026",
            tldr: "Modern automation is cognitive: it uses AI to read unstructured emails, make decisions, extract fields, and route payloads. By combining self-hosted n8n with local LLM connections, companies eliminate variable costs.",
            sections: [
                {
                    title: "1. The Cognitive Automation Paradigm",
                    content: (
                        <div className="space-y-4">
                            <p className="text-zinc-300 leading-relaxed">
                                Traditional automation only moves structured data. Cognitive automation uses LLM reasoning to handle unstructured inputs, such as reading customer emails, identifying sentiment, and executing actions automatically.
                            </p>
                        </div>
                    )
                }
            ],
            faqItems: []
        },
        es: {
            title: "Cómo Automatizar Procesos Corporativos con IA y Plataformas Low-Code (n8n y Make)",
            description: "Explore el cambio de la automatización tradicional a los flujos cognitivos utilizando plataformas autohospedadas como n8n combinadas con LLM.",
            category: "Automação Comercial",
            date: "26 de Junio de 2026",
            tldr: "La automatización moderna es cognitiva: utiliza la IA para procesar correos electrónicos no estructurados, tomar decisiones y ejecutar acciones en los sistemas core.",
            sections: [
                {
                    title: "1. El Paradigma de la Automatización Cognitiva",
                    content: (
                        <div className="space-y-4">
                            <p className="text-zinc-300 leading-relaxed">
                                La automatización tradicional solo mueve datos estructurados. La automatización cognitiva utiliza LLM para interpretar entradas no estructuradas, como correos de clientes.
                            </p>
                        </div>
                    )
                }
            ],
            faqItems: []
        }
    },
    "quanto-custa-desenvolver-um-sistema-web-ou-projeto-de-ia-em-2026": {
        en: {
            title: "How Much Does It Cost to Develop a Web System or AI Project in 2026? (Investment Guide)",
            description: "Check investment tables, delivery timelines, and cost factors in corporate Next.js software engineering, automations, and custom AI.",
            category: "Strategy & Business",
            date: "June 26, 2026",
            tldr: "The investment in custom software projects at GHWD is clearly structured: conversion pages and fast websites cost between R$ 4k and R$ 8k; process automations between R$ 6k and R$ 12k; and custom SaaS or full AI/RAG implementations cost between R$ 15k and R$ 30k+.",
            sections: [
                {
                    title: "1. Price Transparency in Software Engineering",
                    content: (
                        <div className="space-y-4">
                            <p className="text-zinc-300 leading-relaxed">
                                In the B2B software development market, pricing is often obscure and confusing. Many agencies avoid displaying price ranges, generating inflated quotes based on the client's corporate size. At GHWD, we believe in absolute transparency. We structure our investments based on engineering scope, number of API integrations, and architectural complexity.
                            </p>
                            <p className="text-zinc-300 leading-relaxed">
                                Below, we detail our main active investment tiers for the year 2026:
                            </p>
                        </div>
                    )
                },
                {
                    title: "2. General Investment Tiers and Timelines Table",
                    content: (
                        <div className="space-y-6">
                            <div className="overflow-x-auto border border-white/10 rounded-xl">
                                <table className="w-full min-w-[550px] text-left text-sm border-collapse">
                                    <thead>
                                        <tr className="bg-zinc-900 border-b border-white/10">
                                            <th className="p-4 font-bold text-white">Project Category</th>
                                            <th className="p-4 font-bold text-zinc-400">Investment Range</th>
                                            <th className="p-4 font-bold text-emerald-400">Estimated Timeline</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr className="border-b border-white/5">
                                            <td className="p-4 font-semibold text-white">Next.js Landing Pages / Conversion Sites</td>
                                            <td className="p-4 text-zinc-400">R$ 4,000 to R$ 8,000</td>
                                            <td className="p-4 text-zinc-300">2 to 3 weeks</td>
                                        </tr>
                                        <tr className="border-b border-white/5">
                                            <td className="p-4 font-semibold text-white">Institutional Sites / Corporate Portals</td>
                                            <td className="p-4 text-zinc-400">R$ 8,000 to R$ 15,000</td>
                                            <td className="p-4 text-zinc-300">4 to 6 weeks</td>
                                        </tr>
                                        <tr className="border-b border-white/5">
                                            <td className="p-4 font-semibold text-white">Process Automation Workflows (n8n/Make)</td>
                                            <td className="p-4 text-zinc-400">R$ 6,000 to R$ 12,000</td>
                                            <td className="p-4 text-zinc-300">4 to 6 weeks</td>
                                        </tr>
                                        <tr>
                                            <td className="p-4 font-semibold text-white">Bespoke SaaS / AI & RAG Engineering</td>
                                            <td className="p-4 text-zinc-400">R$ 15,000 to R$ 30,000+</td>
                                            <td className="p-4 text-zinc-300">8 to 12 weeks</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    )
                },
                {
                    title: "3. Factors Influencing Development Costs",
                    content: (
                        <div className="space-y-4">
                            <p className="text-zinc-300 leading-relaxed">
                                The final investment of a software project is calculated from specific engineering variables:
                            </p>
                            <ul className="list-disc pl-6 space-y-3 text-zinc-300">
                                <li><strong>Volume of APIs and Integrations:</strong> Connecting a Next.js site to a modern CRM API (e.g. HubSpot) is fast. Integrating asynchronously and bidirectionally with a legacy on-premise ERP without accessible documentation raises testing and development time, and thus cost.</li>
                                <li><strong>Business Rules and Algorithmic Complexity:</strong> Simple contact forms have low costs. Custom SaaS scheduling platforms with proprietary automated banking reconciliation algorithms require more architecture and validation sprints.</li>
                                <li><strong>Security and Compliance Requirements:</strong> Projects with advanced requirements like end-to-end encryption, on-premise container isolation, and detailed audit logs require more complex architectural reviews.</li>
                            </ul>
                        </div>
                    )
                },
                {
                    title: "4. Why Custom Next.js Has Higher ROI than WordPress / No-Code",
                    content: (
                        <div className="space-y-4">
                            <p className="text-zinc-300 leading-relaxed">
                                Many decision-makers choose WordPress or simple page builders to reduce upfront costs. However, in terms of long-term financial return (ROI) and maintenance overhead, GHWD's custom Next.js architecture is significantly cheaper:
                            </p>
                            <ul className="list-disc pl-6 space-y-3 text-zinc-300">
                                <li><strong>Higher Conversion Rate:</strong> For every 100ms of extra delay, your site loses customers. A fast Next.js site (&lt; 1.0s) converts on average 15% to 30% more leads than heavy, sluggish WordPress templates.</li>
                                <li><strong>Low Fixed Maintenance Cost:</strong> Next.js static sites are hosted on low-cost (or free up to millions of visits on Vercel or Netlify) serverless Edge infrastructure. WordPress requires constant plugin updates and expensive dedicated hosting to avoid crashes.</li>
                                <li><strong>Zero Hacking Costs:</strong> Since the exported Next.js interface has no exposed databases or vulnerable admin panels like `/wp-admin`, hacking and data leak rates drop to zero, saving emergency IT expenses and LGPD fines.</li>
                            </ul>
                        </div>
                    )
                }
            ],
            faqItems: [
                {
                    q: "How are project payments divided?",
                    a: "We work with split payments tied to physical milestones in agile bi-weekly sprints. Generally, we structure payments as: Kickoff deposit (20% to 30%), completion of UI/UX Design phase (30% to 40%), and final production launch (30% to 40%), ensuring transparency."
                },
                {
                    q: "Does GHWD charge recurring monthly support fees?",
                    a: "Hosting and serverless infrastructure are kept under the client's own accounts, maintaining full code independence. We provide 30 days of warranty and free post-launch support. We offer optional technical support packages for updates, new features, and security monitoring."
                }
            ]
        },
        es: {
            title: "¿Cuánto Cuesta Desarrollar un Sistema Web o Proyecto de IA en 2026? (Guía de Inversión)",
            description: "Consulte las tablas de inversión, plazos de entrega y factores de costo en ingeniería de software corporativa Next.js, automatizaciones e IA a medida.",
            category: "Estrategia y Negocios",
            date: "26 de Junio de 2026",
            tldr: "La inversión en proyectos de software a medida en GHWD se estructura de forma clara: páginas de conversión y sitios rápidos cuestan de R$ 4k a R$ 8k; automatizaciones de R$ 6k a R$ 12k; y plataformas SaaS o implementaciones completas de IA y RAG de R$ 15k a R$ 30k+.",
            sections: [
                {
                    title: "1. Transparencia de Precios en Ingeniería de Software",
                    content: (
                        <div className="space-y-4">
                            <p className="text-zinc-300 leading-relaxed">
                                En el mercado de desarrollo de software B2B en Brasil, los precios suelen ser oscuros y confusos. Muchas agencias evitan publicar valores, generando presupuestos desproporcionados según el tamaño del cliente. En GHWD, creemos en la transparencia absoluta. Estructuramos nuestras inversiones en función del alcance de la ingeniería, número de integraciones API y complejidad arquitectónica del sistema.
                            </p>
                            <p className="text-zinc-300 leading-relaxed">
                                A continuación, detallamos nuestros principales niveles de inversión vigentes para el año 2026:
                            </p>
                        </div>
                    )
                },
                {
                    title: "2. Tabla General de Rangos de Inversión y Plazos",
                    content: (
                        <div className="space-y-6">
                            <div className="overflow-x-auto border border-white/10 rounded-xl">
                                <table className="w-full min-w-[550px] text-left text-sm border-collapse">
                                    <thead>
                                        <tr className="bg-zinc-900 border-b border-white/10">
                                            <th className="p-4 font-bold text-white">Categoría del Proyecto</th>
                                            <th className="p-4 font-bold text-zinc-400">Rango de Inversión</th>
                                            <th className="p-4 font-bold text-emerald-400">Plazo Estimado</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr className="border-b border-white/5">
                                            <td className="p-4 font-semibold text-white">Next.js Landing Pages / Sitios de Conversión</td>
                                            <td className="p-4 text-zinc-400">R$ 4.000 a R$ 8.000</td>
                                            <td className="p-4 text-zinc-300">2 a 3 semanas</td>
                                        </tr>
                                        <tr className="border-b border-white/5">
                                            <td className="p-4 font-semibold text-white">Sitios Institucionales / Portales Corporativos</td>
                                            <td className="p-4 text-zinc-400">R$ 8.000 a R$ 15.000</td>
                                            <td className="p-4 text-zinc-300">4 a 6 semanas</td>
                                        </tr>
                                        <tr className="border-b border-white/5">
                                            <td className="p-4 font-semibold text-white">Flujos de Automatización de Procesos (n8n/Make)</td>
                                            <td className="p-4 text-zinc-400">R$ 6.000 a R$ 12.000</td>
                                            <td className="p-4 text-zinc-300">4 a 6 semanas</td>
                                        </tr>
                                        <tr>
                                            <td className="p-4 font-semibold text-white">SaaS a Medida / Ingeniería de IA y RAG</td>
                                            <td className="p-4 text-zinc-400">R$ 15.000 a R$ 30.000+</td>
                                            <td className="p-4 text-zinc-300">8 a 12 semanas</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    )
                },
                {
                    title: "3. Factores que Influyen en el Costo de Desarrollo",
                    content: (
                        <div className="space-y-4">
                            <p className="text-zinc-300 leading-relaxed">
                                La inversión final de un proyecto de software se calcula a partir de variables de ingeniería específicas:
                            </p>
                            <ul className="list-disc pl-6 space-y-3 text-zinc-300">
                                <li><strong>Volumen de API e Integraciones:</strong> Conectar un sitio Next.js a una API de CRM moderna (p. ej. HubSpot) es rápido. Integrar de forma bidireccional asíncrona con un ERP heredado antiguo y local sin documentación accesible eleva el tiempo y costo de desarrollo.</li>
                                <li><strong>Reglas de Negocio y Complejidad Algorítmica:</strong> Los formularios de contacto simples tienen costos bajos. Las plataformas SaaS de programación con algoritmos propios de conciliación bancaria automática requieren más sprints de arquitectura.</li>
                                <li><strong>Requisitos de Seguridad y Cumplimiento:</strong> Proyectos con demandas avanzadas de cifrado de extremo a extremo y registros de auditoría requieren revisiones arquitectónicas complejas.</li>
                            </ul>
                        </div>
                    )
                },
                {
                    title: "4. Por Qué el Next.js a Medida tiene Mayor ROI que WordPress / No-Code",
                    content: (
                        <div className="space-y-4">
                            <p className="text-zinc-300 leading-relaxed">
                                Muchos decisores eligen WordPress o creadores simples para reducir el costo inicial. Sin embargo, en términos de retorno financiero a largo plazo (ROI) y costos de operación, la arquitectura Next.js de GHWD es significativamente más barata:
                            </p>
                            <ul className="list-disc pl-6 space-y-3 text-zinc-300">
                                <li><strong>Mayor Tasa de Conversión:</strong> Por cada 100ms de retraso, su sitio pierde clientes. Un sitio Next.js rápido (&lt; 1.0s) convierte entre un 15% y 30% más leads que plantillas pesadas de WordPress.</li>
                                <li><strong>Bajo Costo Fijo de Mantenimiento:</strong> Los sitios estáticos Next.js se alojan en arquitectura serverless Edge de bajo costo. WordPress requiere actualizaciones de plugins constantes y hosting costoso para no caerse.</li>
                                <li><strong>Cero Costos por Hackeos:</strong> Como Next.js no expone bases de datos ni paneles vulnerables como `/wp-admin`, la tasa de hackeos cae a cero, ahorrando costos de TI y multas.</li>
                            </ul>
                        </div>
                    )
                }
            ],
            faqItems: [
                {
                    q: "¿Cómo se dividen los pagos del proyecto?",
                    a: "Trabajamos con pagos por hitos ligados a sprints de dos semanas. Estructuramos los pagos en: Anticipo (20% a 30%), cierre de fase de diseño UI/UX (30% a 40%) y lanzamiento final a producción (30% a 40%)."
                },
                {
                    q: "¿Cobra GHWD tarifas de soporte mensuales recurrentes?",
                    a: "El alojamiento serverless corre por cuenta del cliente, manteniendo la independencia. Ofrecemos 30 dias de garantía y soporte gratuito posterior al lanzamiento, con paquetes opcionales de soporte continuo."
                }
            ]
        }
    }
};

export const servicesTranslations: Record<string, Record<string, Partial<any>>> = {
    "desenvolvimento-web": {
        en: {
            title: "High-Performance Web Development",
            subtitle: "Engineering bespoke, ultra-fast websites, portals, and web applications focused on high conversion rates.",
            tag: "/ Web Engineering",
            tldr: "We build bespoke web ecosystems using Next.js, React, and Tailwind CSS. Our projects achieve maximum Lighthouse scores (100/100), loading times under 1 second, and full compliance with LGPD/GDPR and WCAG accessibility guidelines.",
            metaTitle: "High-Performance Web Development | Next.js & React | GHWD",
            metaDesc: "Bespoke web engineering with Next.js, React, and Tailwind CSS. We develop ultra-fast institutional sites with 100/100 Lighthouse scores and a conversion focus.",
            comparisonTitle: "How does GHWD compare with common platforms?",
            comparisonHeaders: ["Criterion", "Next.js (GHWD)", "Traditional WordPress", "No-Code (Wix/Webflow)"],
            comparisonRows: [
                ["Speed (LCP)", "< 1.0s (Excellent)", "2.8s to 4.5s (Poor)", "2.2s to 3.5s (Average)"],
                ["Security", "Extreme (No exposed databases on Edge)", "Vulnerable (Third-party plugins)", "Platform Dependent"],
                ["DOM Structure", "Linear and Clean (No code bloat)", "Excessive div nesting (Bloat)", "Heavy proprietary structure"],
                ["AI SEO & GEO", "Optimized (JSON-LD and RAG injection)", "Limited to basic plugins", "Little control over fine metadata"],
                ["Maintainability", "High (Clean TypeScript codebase)", "Complex (Breaks after updates)", "Limited to tool limits"]
            ],
            faqTitle: "Common Questions about Web Software Engineering",
            faqItems: [
                {
                    q: "Why is loading speed vital for my business?",
                    a: "Speed is not just an aesthetic metric. Google penalizes slow websites by lowering their search ranking. Furthermore, statistics prove that for every 100ms of extra loading delay, conversion rates drop by up to 7%. An under-1-second loading site guarantees maximum retention and sales."
                }
            ]
        },
        es: {
            title: "Desarrollo Web de Alto Rendimiento",
            subtitle: "Ingeniería de sitios, portales y aplicaciones web a medida, ultrarrápidos y enfocados en alta conversión.",
            tag: "/ Ingeniería Web",
            tldr: "Desarrollamos ecosistemas web a medida utilizando Next.js, React y Tailwind CSS. Nuestros proyectos logran la puntuación máxima (100/100) en Lighthouse, carga inferior a 1 segundo y cumplimiento total con LGPD/GDPR y pautas WCAG.",
            metaTitle: "Desarrollo Web de Alto Rendimiento | Next.js & React | GHWD",
            metaDesc: "Ingeniería web a medida con Next.js, React y Tailwind CSS. Desarrollamos sitios institucionales ultrarrápidos con nota 100/100 en Lighthouse y enfoque en conversión.",
            comparisonTitle: "¿Cómo se compara GHWD con plataformas comunes?",
            comparisonHeaders: ["Criterio", "Next.js (GHWD)", "WordPress Tradicional", "No-Code (Wix/Webflow)"],
            comparisonRows: [
                ["Velocidad (LCP)", "< 1.0s (Excelente)", "2.8s a 4.5s (Malo)", "2.2s a 3.5s (Medio)"],
                ["Seguridad", "Extrema (Sin base de datos expuesta)", "Vulnerable (Plugins de terceros)", "Dependiente de la plataforma"],
                ["Estructura DOM", "Lineal y Limpia (Sin código basura)", "Exceso de divs anidados (Bloat)", "Estructura propietaria pesada"],
                ["AI SEO & GEO", "Optimizado (Inyección de JSON-LD y RAG)", "Limitado a plugins básicos", "Poco control sobre metadatos finos"],
                ["Mantenibilidad", "Alta (Código limpio con TypeScript)", "Compleja (Rotura tras actualizaciones)", "Limitada a los límites de la herramienta"]
            ],
            faqTitle: "Preguntas Frecuentes sobre Ingeniería de Software Web",
            faqItems: [
                {
                    q: "¿Por qué la velocidad de carga es vital para mi negocio?",
                    a: "La velocidad no es solo estética. Google penaliza los sitios lentos reduciendo su posicionamiento. Además, las estadísticas demuestran que por cada 100ms extras de retraso en la carga, las conversiones de ventas pueden caer un 7%."
                }
            ]
        }
    },
    "automacao-empresarial": {
        en: {
            title: "Corporate Workflow & Process Automation",
            subtitle: "Connecting systems, orchestrating APIs, and creating automated flows that eliminate manual tasks.",
            tag: "/ Process Automation",
            tldr: "We replace human error with automated code. We integrate legacy ERPs, payment gateways, and CRM pipelines using secure APIs and self-hosted n8n/Make platforms, reducing operational costs by up to 80%.",
            comparisonTitle: "Manual Processes vs. Automated Engineering",
            comparisonHeaders: ["Process", "Manual Workflow", "Automated System (GHWD)"],
            comparisonRows: [
                ["Invoice Issuance", "Requires copy-pasting from ERP to bank (5 min)", "Automatic Webhook triggers bancary API instantly (100ms)"],
                ["Logistics Update", "SDR checks shipping code manually", "System updates CRM & alerts client automatically"],
                ["Error Rates", "Typing errors, double entries, lost leads", "Zero typing errors, guaranteed validation"],
                ["Scalability", "Limited to workforce hours", "Infinite scale, processes 24/7 in cloud"]
            ],
            faqTitle: "Common Questions about Process Automation",
            faqItems: [
                {
                    q: "What is n8n and why does GHWD prefer it over other tools?",
                    a: "n8n is a powerful workflow automation engine. Unlike tools like Zapier, n8n can be self-hosted on the client's own cloud. This means there are no variable monthly execution fees, and complete data privacy is maintained as customer data never leaves your secure server."
                }
            ]
        },
        es: {
            title: "Automatización de Procesos y Flujos Corporativos",
            subtitle: "Conectando sistemas, orquestando API y creando flujos automatizados que eliminan las tareas manuales.",
            tag: "/ Automatización de Procesos",
            tldr: "Reemplazamos las tareas manuales por código automatizado. Integramos ERP heredados, pasarelas de pago y CRM utilizando API seguras y n8n/Make autohospedado, reduciendo costos operativos hasta un 80%.",
            comparisonTitle: "Procesos Manuales vs. Ingeniería de Automatización",
            comparisonHeaders: ["Proceso", "Flujo Manual", "Sistema Automatizado (GHWD)"],
            comparisonRows: [
                ["Emisión de Facturas", "Requiere copiar datos de ERP a banco (5 min)", "Webhook automático activa API de inmediato (100ms)"],
                ["Actualización de Logística", "El personal revisa y envía códigos manualmente", "El sistema actualiza el CRM y alerta al cliente automáticamente"],
                ["Tasa de Errores", "Errores tipográficos, leads perdidos", "Cero errores tipográficos, validación garantizada"],
                ["Escalabilidad", "Limitada por horas de personal", "Escalabilidad infinita, procesa 24/7 en la nube"]
            ],
            faqTitle: "Preguntas Frecuentes sobre Automatización de Procesos",
            faqItems: [
                {
                    q: "¿Qué es n8n y por qué GHWD lo prefiere sobre otras herramientas?",
                    a: "n8n es un potente motor de automatización. A diferencia de Zapier, n8n se puede autohospedar en la nube del cliente. Esto elimina tarifas mensuales variables por ejecución y mantiene la total privacidad de los datos."
                }
            ]
        }
    },
    "inteligencia-artificial": {
        en: {
            title: "Custom AI Development & Agent Integration",
            subtitle: "Engineering autonomous cognitive agents, secure RAG setups, and custom AI tools for enterprise roadmaps.",
            tag: "/ AI & Agents",
            tldr: "We develop custom AI solutions using LLMs, vector search (RAG), and Anthropics' Model Context Protocol (MCP). We build tools that reason in a loop to handle complex tasks like automated level-2 support and SDR outreach.",
            comparisonTitle: "Out-of-the-box AI vs. Custom Engineering",
            comparisonHeaders: ["Metric", "Generic ChatGPT Setup", "Custom AI Agents (GHWD)"],
            comparisonRows: [
                ["Knowledge Source", "Public web data, generic training weights", "Your company databases, ERP records, and secure manuals"],
                ["Hallucination Rates", "High (Creates facts when unsure)", "Near zero (Anchored to RAG context verification)"],
                ["Actions", "Reads and writes text only", "Triggers APIs, updates systems, and schedules meetings"],
                ["Security", "Data used for public model training", "Fully private data loops with enterprise privacy agreements"]
            ],
            faqTitle: "Common Questions about Custom AI Integrations",
            faqItems: [
                {
                    q: "How do you guarantee that the AI won't fabricate data (hallucinate)?",
                    a: "We implement Retrieval-Augmented Generation (RAG). Before answering, the system retrieves relevant facts from a secure corporate vector database. The LLM is then strictly instructed to answer using only that verified context, reducing hallucinations to practically zero."
                }
            ]
        },
        es: {
            title: "Desarrollo de IA a Medida e Integración de Agentes",
            subtitle: "Ingeniería de agentes cognitivos autónomos, configuraciones de RAG seguras y herramientas de IA personalizadas.",
            tag: "/ IA y Agentes",
            tldr: "Desarrollamos soluciones de IA a medida utilizando LLMs, búsqueda vectorial (RAG) y Model Context Protocol (MCP) de Anthropic. Construimos herramientas que razonan en bucle para tareas complejas.",
            comparisonTitle: "IA Genérica vs. Ingeniería a Medida",
            comparisonHeaders: ["Métrica", "ChatGPT Genérico", "Agentes de IA a Medida (GHWD)"],
            comparisonRows: [
                ["Fuente de Datos", "Datos públicos de la web", "Bases de datos de su empresa, registros de ERP y manuales"],
                ["Tasa de Alucinaciones", "Alta (Inventa hechos al dudar)", "Casi cero (Anclada a la verificación de contexto RAG)"],
                ["Acciones", "Solo lee y escribe texto", "Activa API, actualiza sistemas y agenda reuniones"],
                ["Seguridad", "Datos compartidos para entrenamiento público", "Bucles de datos privados con acuerdos de privacidad corporativa"]
            ],
            faqTitle: "Preguntas Frecuentes sobre Integración de IA",
            faqItems: [
                {
                    q: "¿Cómo garantizan que la IA no inventará datos (alucinará)?",
                    a: "Implementamos RAG. Antes de responder, el sistema busca datos reales en una base de datos vectorial corporativa segura. Se instruye estrictamente al LLM para que responda usando únicamente ese contexto verificado."
                }
            ]
        }
    },
    "integracoes": {
        en: {
            title: "Enterprise Systems Integration & Sync Pipelines",
            subtitle: "Connecting legacy systems, ERPs, CRMs, and APIs in robust, event-driven pipelines.",
            tag: "/ Integrations",
            tldr: "We design robust integrations using RabbitMQ, SQS, and S3. We build secure middlewares that connect systems, handle backoffs, and sync data in real-time, preventing errors and lag.",
            comparisonTitle: "Point-to-Point vs. Event-Driven Architecture",
            comparisonHeaders: ["Aspect", "Point-to-Point integrations", "Event-Driven Synapse (GHWD)"],
            comparisonRows: [
                ["Network Failures", "Transaction fails, data gets lost", "Transaction stored in queues, retried automatically"],
                ["ERP Performance", "ERP slows down due to direct hits", "ERP protected by queues, processing in batches"],
                ["Data Sync Lag", "Periodic batch updates (minutes/hours)", "Real-time updates triggered on event (milliseconds)"],
                ["Audit Trail", "Hard to debug, silent errors", "Structured logs of payload and status for every call"]
            ],
            faqTitle: "Common Questions about System Integrations",
            faqItems: [
                {
                    q: "How does the system handle integrations when the destination is offline?",
                    a: "We use message queuing (like Redis or SQS). If the receiving system (like your ERP) goes offline, the transactions wait safely in the queue. When the system comes back online, the transactions are processed automatically in order, without any loss."
                }
            ]
        },
        es: {
            title: "Integración de Sistemas y Flujos de Sincronización",
            subtitle: "Conectando sistemas heredados, ERP, CRM y API en canalizaciones sólidas basadas en eventos.",
            tag: "/ Integraciones",
            tldr: "Diseñamos integraciones robustas utilizando RabbitMQ, SQS y S3. Construimos middlewares seguros que conectan sistemas, manejan reintentos y sincronizan datos en tiempo real.",
            comparisonTitle: "Integración Punto a Punto vs. Basada en Eventos",
            comparisonHeaders: ["Aspecto", "Conexión Punto a Punto", "Synapse Basado en Eventos (GHWD)"],
            comparisonRows: [
                ["Fallos de Red", "La transacción falla, los datos se pierden", "La transacción se guarda en colas y se reintenta automáticamente"],
                ["Rendimiento ERP", "El ERP se ralentiza por consultas directas", "El ERP está protegido por colas, procesa por lotes"],
                ["Retraso de Datos", "Actualizaciones periódicas por lotes", "Actualizaciones en tiempo real activadas por eventos"],
                ["Seguimiento de Auditoría", "Difícil de depurar, fallos silenciosos", "Registros estructurados del payload y estado de cada llamada"]
            ],
            faqTitle: "Preguntas Frecuentes sobre Integración de Sistemas",
            faqItems: [
                {
                    q: "¿Cómo maneja el sistema las integraciones si el destino está desconectado?",
                    a: "Utilizamos colas de mensajería (como Redis o SQS). Si el sistema de destino se desconecta, las transacciones esperan de forma segura en la cola. Al reconectarse, se procesan automáticamente en orden."
                }
            ]
        }
    },
    "arquitetura-de-projetos": {
        en: {
            title: "Software Architecture & High-Performance Projects",
            subtitle: "Architectural design, cloud infrastructure audits, security, and technical roadmaps focused on delivering solid, scalable projects.",
            tag: "/ Projects & Architecture",
            tldr: "We structure the foundation and technical architecture to guarantee the delivery of scalable digital projects. We perform code and server audits, plan cloud migrations, and establish robust data governance under LGPD/GDPR.",
            comparisonTitle: "Other Agencies vs. GHWD Project Engineering",
            comparisonHeaders: ["Focus", "Generic Agency (Slides & Theory)", "Project Engineering (GHWD)"],
            comparisonRows: [
                ["Delivery", "Theoretical slides and abstract planning that rarely get implemented", "Real software projects, functional architectures ready for production, and clean code"],
                ["Assessment", "Superficial checks based on basic templates", "Deep codebase audit performed directly by senior engineers and architects"],
                ["Cloud Infra", "Recommending cloud providers without analyzing traffic", "Serverless cloud architecture with 30% to 50% cost reductions in servers"],
                ["Security", "Generic and bureaucratic security templates", "Practical end-to-end encryption implementation and robust data governance"],
                ["Results", "Static PDF reports archived in folders", "Validated prototypes, frequent incremental releases, and support until deployment"]
            ],
            faqTitle: "Common Questions about Architecture and Project Engineering",
            faqItems: [
                {
                    q: "Why invest in architecture design before starting the software build?",
                    a: "Technical planning models the foundation, data flows, and integration limits. This upfront work prevents database errors or incorrect technology selections that cause delays, cloud cost overrides, or the need to rebuild from scratch."
                }
            ]
        },
        es: {
            title: "Arquitectura de Software y Proyectos de Alto Rendimiento",
            subtitle: "Diseño arquitectónico, auditorías de infraestructura en la nube, seguridad y roadmaps técnicos para entregar proyectos sólidos.",
            tag: "/ Proyectos y Arquitectura",
            tldr: "Estructuramos la base y arquitectura técnica para garantizar la entrega de proyectos digitales escalables. Realizamos auditorías de código, planificamos migraciones y establecemos gobernanza de datos.",
            comparisonTitle: "Otras Agencias vs. Ingeniería de Proyectos GHWD",
            comparisonHeaders: ["Enfoque", "Agencias Genéricas (Slides y Teoría)", "Ingeniería de Proyectos (GHWD)"],
            comparisonRows: [
                ["Entrega", "Diapositivas teóricas y planes abstractos que rara vez se implementan", "Proyectos de software reales, arquitectura en producción y código limpio"],
                ["Evaluación", "Revisiones superficiales basadas en plantillas", "Auditoría profunda de código realizada por ingenieros senior"],
                ["Infraestructura Nube", "Sugerencias de proveedores sin análisis de tráfico", "Arquitectura serverless con reducciones del 30% al 50% en servidores"],
                ["Seguridad", "Modelos de seguridad genéricos", "Implementación práctica de cifrado de extremo a extremo y gobernanza"],
                ["Resultados", "Informes estáticos en PDF guardados en carpetas", "Prototipos validados, entregas incrementales y despliegue final"]
            ],
            faqTitle: "Preguntas Frecuentes sobre Arquitectura e Ingeniería de Proyectos",
            faqItems: [
                {
                    q: "¿Por qué invertir en diseño de arquitectura antes de iniciar el desarrollo?",
                    a: "El diseño técnico define las bases, flujos y límites de integración del sistema. Previene errores de base de datos o elecciones de tecnologías incorrectas que generan costos adicionales."
                }
            ]
        }
    }
};

export const citiesTranslations: Record<string, Record<string, Partial<any>>> = {
    "farroupilha": {
        en: {
            region: "Serra Gaúcha Hills",
            country: "Brazil",
            businessContext: "strong industrial metal-mechanical hub, textile and footwear industries, and the traditional knitwear commerce of Serra Gaúcha"
        },
        es: {
            region: "Serra Gaúcha",
            country: "Brasil",
            businessContext: "fuerte polo industrial metalmecánico, industrias textiles y del calzado, y el tradicional comercio de tejidos de Serra Gaúcha"
        }
    },
    "caxias-do-sul": {
        en: {
            region: "Serra Gaúcha Hills",
            country: "Brazil",
            businessContext: "second largest metal-mechanical hub in Brazil, with a strong presence of automotive, metallurgical industries and robust commerce"
        },
        es: {
            region: "Serra Gaúcha",
            country: "Brasil",
            businessContext: "segundo mayor polo metalmecánico de Brasil, con fuerte presencia de industrias automotrices, metalúrgicas y comercio robusto"
        }
    },
    "bento-goncalves": {
        en: {
            region: "Serra Gaúcha Hills",
            country: "Brazil",
            businessContext: "leading furniture manufacturing hub in the country, internationally recognized wine region, and strong tourism sector"
        },
        es: {
            region: "Serra Gaúcha",
            country: "Brasil",
            businessContext: "principal polo fabricante de muebles del país, región vinícola de referencia internacional y fuerte sector turístico"
        }
    },
    "porto-alegre": {
        en: {
            region: "Greater Porto Alegre",
            country: "Brazil",
            businessContext: "metropolitan innovation hub, tech startup ecosystem, corporate services, and state capital of Rio Grande do Sul"
        },
        es: {
            region: "Gran Porto Alegre",
            country: "Brasil",
            businessContext: "hub metropolitano de innovación, ecosistema de startups tecnológicas, servicios corporativos y capital del estado"
        }
    },
    "sao-paulo": {
        en: {
            region: "Greater São Paulo",
            country: "Brazil",
            businessContext: "primary financial, corporate, and technological center of Latin America, hosting multinational headquarters and tech giants"
        },
        es: {
            region: "Gran São Paulo",
            country: "Brasil",
            businessContext: "principal centro financiero, corporativo y tecnológico de América Latina, albergando sedes de multinacionales y gigantes de la tecnología"
        }
    },
    "lisboa": {
        en: {
            region: "Greater Lisbon",
            country: "Portugal",
            businessContext: "expanding European technology hub, vibrant tech startup ecosystem, high-end tourism, and international business"
        },
        es: {
            region: "Gran Lisboa",
            country: "Portugal",
            businessContext: "hub tecnológico europeo en expansión, vibrante ecosistema de startups tecnológicas, turismo de alta gama y negocios internacionales"
        }
    },
    "madrid": {
        en: {
            region: "Community of Madrid",
            country: "Spain",
            businessContext: "financial and economic center of the Iberian Peninsula, with a high concentration of multinational corporate headquarters and advanced engineering services"
        },
        es: {
            region: "Comunidad de Madrid",
            country: "España",
            businessContext: "centro financiero y económico de la Península Ibérica, con una alta concentración de sedes corporativas multinacionales y servicios avanzados de ingeniería"
        }
    },
    "nova-york": {
        en: {
            region: "NYS",
            country: "USA",
            businessContext: "world financial capital, hub of disruptive software innovation, global media, and high-scale international business"
        },
        es: {
            region: "NYS",
            country: "EE.UU.",
            businessContext: "capital financiera mundial, polo de innovación disruptiva de software, medios globales y negocios internacionales a gran escala"
        }
    }
};
